### ISSUE TITLE
Getting java.lang.UnsatisfiedLinkError: No implementation found for boolean com.microsoft.applications.events.Utils.validateEventName(java.lang.String)

### ISSUE THREAD

**Issue by prabhavsharma** [microsoft/cpp_client_telemetry#928]
We are getting the belove exception on App launch on Emulator : 
`09-10 01:33:26.078 14629 14880 E AndroidRuntime: java.lang.UnsatisfiedLinkError: No implementation found for boolean com.microsoft.applications.events.Utils.validateEventName(java.lang.String) (tried Java_com_microsoft_applications_events_Utils_validateEventName and Java_com_microsoft_applications_events_Utils_validateEventName__Ljava_lang_String_2)
09-10 01:33:26.078 14629 14880 E AndroidRuntime: 	at com.microsoft.applications.events.Utils.validateEventName(Native Method)
09-10 01:33:26.078 14629 14880 E AndroidRuntime: 	at com.microsoft.applications.events.EventProperties.setName(EventProperties.java:92)
09-10 01:33:26.078 14629 14880 E AndroidRuntime: 	at com.microsoft.applications.events.EventProperties.<init>(EventProperties.java:25)
09-10 01:33:26.078 14629 14880 E AndroidRuntime: 	at com.microsoft.applications.events.EventProperties.<init>(EventProperties.java:39)
09-10 01:33:26.078 14629 14880 E AndroidRuntime: 	at com.microsoft.teams.telemetry.util.OneDSLoggerHelper.convertToOneDSEventProperties(OneDSLoggerHelper.java:56)`

**Steps to reproduce.**
This has been happening on Emulators on our CI pipelines. 

**What is the expected behavior?**
What did you expect to see?

**What is the actual behavior?**
What did you see instead?

**Additional context.**
We are using gradle dependencies to get the com.microsoft.applications.events:maesdk: 
Also on opening the zip file of the apk we can see that the .so file for maesdk is present and is happening on  (x86 architecture)

**Comment by lalitb** [comment]
@prabhavsharma  - Have you gone through the issue ( https://github.com/microsoft/cpp_client_telemetry/issues/624 ) if that helps?

**Comment by lalitb** [comment]
@suryatn  - As you had earlier faced a similar error, in case you can provide some pointers.

**Comment by suryatn** [comment]
@lalitb I think this is some other issue and caused due to some code change on the client side. @prabhavsharma can confirm if this is resolved now. cc @aamittal1989

**Comment by lalitb** [comment]
Thanks, @suryatn.
@prabhavsharma  - Are you still facing this issue?
