### ISSUE TITLE
JNI error while initializing PrivacyGuard

### ISSUE THREAD

**Issue by abbytran1996** [microsoft/cpp_client_telemetry#989]
Recently, I pulled in changes from cpp_client_telemetry to our` outlookmobile/droid branch` using this commit: https://github.com/microsoft/cpp_client_telemetry/commit/c315da21838d14c195dd1de2500c7e99304e7f0d

After building and implementing these changes:
![Screen Shot 2022-01-28 at 11 31 28 AM](https://user-images.githubusercontent.com/22625926/151594179-34ea8568-89a2-4dba-9744-7fce321c3d9b.png)

...we got this boot ANR and the error was from `nativeInitializePrivacyGuard()`. Even when I commented out the `pgConfig.DisableAdvancedScans = true;` line, the error still happened

```
runtime.cc:655]   at com.microsoft.applications.events.PrivacyGuard.nativeInitializePrivacyGuard(Native method)
    runtime.cc:655]   at com.microsoft.applications.events.PrivacyGuard.initialize(PrivacyGuard.java:56)
    runtime.cc:655]   at com.acompli.acompli.providers.AriaEventLogger.initializeOneDSLogger(AriaEventLogger.java:121)
    runtime.cc:655]   at com.acompli.acompli.providers.AriaEventLogger.initializeLogger(AriaEventLogger.java:87)
    runtime.cc:655]   at com.acompli.acompli.providers.MainAriaEventLogger.<init>(MainAriaEventLogger.java:303)
    runtime.cc:655]   at com.acompli.acompli.providers.AriaEventLogger.<init>(AriaEventLogger.java:71)
    runtime.cc:655]   at com.acompli.acompli.providers.AriaEventLogger.createInstance(AriaEventLogger.java:51)
    runtime.cc:655]   - locked <0x0b8d0112> (a java.lang.Object)
    runtime.cc:655]   at com.microsoft.office.outlook.boot.componentsdependent.AriaWorkItem.initialize(AriaWorkItem.java:29)
    runtime.cc:655]   at com.microsoft.office.outlook.boot.componentsdependent.ComponentsDependentBootstrapOrchestrator.lambda$getInitializeTask$2(ComponentsDependentBootstrapOrchestrator.java:246)
    runtime.cc:655]   at com.microsoft.office.outlook.boot.componentsdependent.ComponentsDependentBootstrapOrchestrator$$ExternalSyntheticLambda2.call(unavailable:-1)
    runtime.cc:655]   at bolts.Task$4.run(Task.java:386)
    runtime.cc:655]   at com.microsoft.office.outlook.profiling.ProfiledRunnable.run(ProfiledRunnable.java:62)
    runtime.cc:655]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    runtime.cc:655]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    runtime.cc:655]   at com.microsoft.office.outlook.executors.PrioritizingRunnable.run(PrioritizingRunnable.java:26)
    runtime.cc:655]   at java.lang.Thread.run(Thread.java:923)
    runtime.cc:655] 
A/ice.outlook.de: runtime.cc:663] JNI DETECTED ERROR IN APPLICATION: jstring has wrong type: java.lang.Object[]
    runtime.cc:663]     in call to GetStringUTFLength
    runtime.cc:663]     from boolean com.microsoft.applications.events.PrivacyGuard.nativeInitializePrivacyGuard(long, java.lang.String, java.lang.String, java.lang.String, boolean, boolean, java.lang.String, java.lang.String, java.lang.Object[], java.lang.Object[], java.lang.Object[], java.lang.Object[], java.lang.Object[], java.lang.Object[])
```

From the last time we updated our 1DS library, the only Privacy Guard-related changes were from this commit: https://github.com/microsoft/cpp_client_telemetry/commit/c18ed6c034f9abc748e266f781a1a2481cfc32fc, but I'm not sure how it caused this error. I will need your expertises on this!

I have also opened another ticket that maybe related to this error here: https://github.com/microsoft/cpp_client_telemetry/issues/988

**Comment by lalitb** [comment]
Assigning to @sid-dahiya in case he can help here.
